from itemData_update import *

probableNegations = itemData(
["can rule out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["cannot be excluded","PROBABLE_NEGATED_EXISTENCE",r"""cannot\sbe\s((entirely|completely)\s)?(excluded|ruled out)""","backward"],
["is not excluded","PROBABLE_NEGATED_EXISTENCE",r"""(is|was|are|were)\snot\sexcluded""",'backward'],
["adequate to rule the patient out against","PROBABLE_NEGATED_EXISTENCE","","forward"],
["can rule him out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["not know of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no findings of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["sufficient to rule her out against","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no suggestion of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["adequate to rule him out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["sufficient to rule him out against","PROBABLE_NEGATED_EXISTENCE",r"""sufficient\sto\srule\s(him|her)\sout\sagainst""","forward"],
["not reveal","PROBABLE_NEGATED_EXISTENCE","","forward"],
["can rule the patient out for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["adequate to rule her out for","PROBABLE_NEGATED_EXISTENCE",r"""adequate\sto\srule\s(her|him)\sout\sfor""","forward"],
["sufficient to rule her out for","PROBABLE_NEGATED_EXISTENCE",r"""sufficient\sto\srule\s(her|him)\sout\sfor""","forward"],
["adequate to rule out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["can rule the patient out against","PROBABLE_NEGATED_EXISTENCE",r"""can\srule\s(her|him)\sout\sagainst""","forward"],
["can rule him out against","PROBABLE_NEGATED_EXISTENCE",r"""can\srule\s(her|him)\sout\sagainst""","forward"],
["rather than","PROBABLE_NEGATED_EXISTENCE","","forward"],
["nothing","PROBABLE_NEGATED_EXISTENCE","","forward"],
["not exhibit","PROBABLE_NEGATED_EXISTENCE","","forward"],
["checked for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["evaluate for","PROBABLE_NEGATED_EXISTENCE","","forward"], ### SHOULD THIS BE AN INDICATION?
["can rule the patient out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no findings to indicate","PROBABLE_NEGATED_EXISTENCE","","forward"],
["free","PROBABLE_NEGATED_EXISTENCE","","backward"],
["sufficient to rule him out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["can rule out against","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no sign of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no definite","PROBABLE_NEGATED_EXISTENCE", r"""no[\s]*definite""","forward"], #fixes peco #188, #255
["without sign of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["adequate to rule the patient out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["can rule her out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["sufficient to rule him out for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no significant","PROBABLE_NEGATED_EXISTENCE","","forward"],
["adequate to rule him out for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["not feel","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no obvious","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no complaints of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["not associated with","PROBABLE_NEGATED_EXISTENCE","","forward"],
["can rule out for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["can rule her out for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["adequate to rule out for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["not see","PROBABLE_NEGATED_EXISTENCE","","forward"],
["fails to reveal","PROBABLE_NEGATED_EXISTENCE","","forward"],
["to exclude","PROBABLE_NEGATED_EXISTENCE","","forward"],
["sufficient to rule the patient out for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["sufficient to rule out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["unremarkable for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["not appreciate","PROBABLE_NEGATED_EXISTENCE","","forward"],
["not complain of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["not demonstrate","PROBABLE_NEGATED_EXISTENCE","","forward"],
["not to be","PROBABLE_NEGATED_EXISTENCE","","forward"],
["unlikely","PROBABLE_NEGATED_EXISTENCE","","backward"],
["absence of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["adequate to rule her out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["can rule him out for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["denying","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no signs of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no abnormal","PROBABLE_NEGATED_EXISTENCE","","forward"],
["sufficient to rule the patient out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["without indication of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["sufficient to rule her out","PROBABLE_NEGATED_EXISTENCE","","forward"],
["adequate to rule the patient out for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["cannot see","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no cause of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["no evidence of","PROBABLE_NEGATED_EXISTENCE","","forward"],
["not known to have","PROBABLE_NEGATED_EXISTENCE","","forward"],
["can rule her out against","PROBABLE_NEGATED_EXISTENCE",r"""can\srule\s(her|him)\sout\sagainst""","forward"],
["sufficient to rule her out for","PROBABLE_NEGATED_EXISTENCE",r"""sufficient\sto\srule\s(her|him)\sout\sfor""","forward"],
["sufficient to rule the patient out against","PROBABLE_NEGATED_EXISTENCE","","forward"],
["sufficient to rule out against","PROBABLE_NEGATED_EXISTENCE","","forward"],
["sufficient to rule out for","PROBABLE_NEGATED_EXISTENCE","","forward"],
["test for","PROBABLE_NEGATED_EXISTENCE","","forward"],
)

definiteNegations = itemData(
["deny","DEFINITE_NEGATED_EXISTENCE","","forward"],
["denied","DEFINITE_NEGATED_EXISTENCE","","forward"],
["denies","DEFINITE_NEGATED_EXISTENCE","","forward"],
["declined","DEFINITE_NEGATED_EXISTENCE","","forward"],
["declines","DEFINITE_NEGATED_EXISTENCE","","forward"],
["ruled him out against","DEFINITE_NEGATED_EXISTENCE","","forward"],
["did rule her out against","DEFINITE_NEGATED_EXISTENCE","","forward"],
["are ruled out","DEFINITE_NEGATED_EXISTENCE","","backward"],
["rules the patient out for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["ruled her out against","DEFINITE_NEGATED_EXISTENCE","""ruled\s(him|her)\sout\sagainst""","forward"],
["ruled her out","DEFINITE_NEGATED_EXISTENCE","","forward"],
["rules him out for","DEFINITE_NEGATED_EXISTENCE",r"""rules\s(him|her)\sout\sfor""","forward"],
["rules out","DEFINITE_NEGATED_EXISTENCE","","forward"],
["no other", "DEFINITE_NEGATED_EXISTENCE", r"""no[\s]*other""","forward"], #fixes pedoc #265
["ruled the patient out against","DEFINITE_NEGATED_EXISTENCE","","forward"],
["is ruled out","DEFINITE_NEGATED_EXISTENCE","","backward"],
["did rule the patient out","DEFINITE_NEGATED_EXISTENCE","","forward"],
["ruled him out against","DEFINITE_NEGATED_EXISTENCE","","forward"],
["cannot","DEFINITE_NEGATED_EXISTENCE","","forward"],
["negative for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["is negative","DEFINITE_NEGATED_EXISTENCE",r"(is|was) negative","backward"],
["-ve for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["not","DEFINITE_NEGATED_EXISTENCE",r"\bnot\b","forward"],
["never had","DEFINITE_NEGATED_EXISTENCE","","forward"],
["did rule the patient out against","DEFINITE_NEGATED_EXISTENCE","","forward"],
["patient was not","DEFINITE_NEGATED_EXISTENCE","","forward"],
["has been ruled out","DEFINITE_NEGATED_EXISTENCE","","backward"],
["rules her out for","DEFINITE_NEGATED_EXISTENCE",r"""rules\s(him|her)\sout\sfor""","forward"],
["with no","DEFINITE_NEGATED_EXISTENCE","","forward"],
["not had","DEFINITE_NEGATED_EXISTENCE","","forward"],
["rules him out","DEFINITE_NEGATED_EXISTENCE",r"""rules\s(him|her|the\spatient)\sout""","forward"],
["did rule the patient out for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["did rule out for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["did rule him out against","DEFINITE_NEGATED_EXISTENCE","","forward"],
["ruled him out","DEFINITE_NEGATED_EXISTENCE","","forward"],
["no new","DEFINITE_NEGATED_EXISTENCE","","forward"],
["ruled her out for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["did rule out against","DEFINITE_NEGATED_EXISTENCE","","forward"],
["did rule her out for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["did rule him out for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["free of","DEFINITE_NEGATED_EXISTENCE","","forward"],
["not have","DEFINITE_NEGATED_EXISTENCE","","forward"],
["ruled the patient out","DEFINITE_NEGATED_EXISTENCE","","forward"],
["ruled out","DEFINITE_NEGATED_EXISTENCE","","forward"],
["ruled out against","DEFINITE_NEGATED_EXISTENCE","","forward"],
["negative examination for","DEFINITE_NEGATED_EXISTENCE",r"negative (examination|study|exam|evaluation) for","forward"],
["rules out for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["rules her out","DEFINITE_NEGATED_EXISTENCE","","forward"],
["ruled out for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["resolved","DEFINITE_NEGATED_EXISTENCE","","backward"],
["ruled him out for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["did rule him out","DEFINITE_NEGATED_EXISTENCE","","forward"],
["no","DEFINITE_NEGATED_EXISTENCE",r"\bno\b","forward"],
["was ruled out","DEFINITE_NEGATED_EXISTENCE","","backward"],
["did rule her out against","DEFINITE_NEGATED_EXISTENCE","","forward"],
["did rule out","DEFINITE_NEGATED_EXISTENCE","","forward"],
["ruled the patient out for","DEFINITE_NEGATED_EXISTENCE","","forward"],
["never developed","DEFINITE_NEGATED_EXISTENCE","","forward"],
["did rule her out","DEFINITE_NEGATED_EXISTENCE","","forward"],
["without","DEFINITE_NEGATED_EXISTENCE","","forward"],
["have been ruled out","DEFINITE_NEGATED_EXISTENCE","","backward"],
)

pseudoNegations = itemData(
["not only","PSEUDONEG","",""],
["no definite change","PSEUDONEG","","forward"],
["not cause","PSEUDONEG","","forward"], #should have a re for "not (the) cause"
["without difficulty","PSEUDONEG","","forward"],
["not extend","PSEUDONEG","","forward"],
["not necessarily","PSEUDONEG","","forward"],
["not certain whether","PSEUDONEG","","forward"],
["no significant change","PSEUDONEG","","forward"],
["no suspicious change","PSEUDONEG","","forward"],
["no increase","PSEUDONEG","","forward"],
["no significant interval change","PSEUDONEG","","forward"],
["not drain","PSEUDONEG","","forward"],
["gram negative","PSEUDONEG","","forward"],
["no change","PSEUDONEG","","forward"],
["risk factors for","PSEUDONEG","","forward"],
#["the examination","PSEUDONEG","","backward"],
#["positive study for","PSEDUONEG",r"positive (study|exam|examination)( for)","forward"],
)

indications = itemData(
["will be ruled out","INDICATION","","backward"],
["can be ruled out","INDICATION","","backward"],
["will be ruled out for","INDICATION","","forward"],
["should be ruled out","INDICATION","","backward"],
#["did not rule out","INDICATION","","backward"],
["rule out","INDICATION",r"(r/o|rule out|\br o\b|r\.o\.|\bro\b)","forward"],
["could be ruled out","INDICATION","","backward"],
#["not ruled out","INDICATION","","backward"],
["ought to be ruled out for","INDICATION","","forward"],
["be ruled out","INDICATION","","backward"],
["could be ruled out for","INDICATION","","forward"],
["must be ruled out","INDICATION","","backward"],
["must be ruled out for","INDICATION","","forward"],
["ought to be ruled out","INDICATION","","backward"],
["can be ruled out for","INDICATION","","forward"],
["rule him out for","INDICATION","","forward"],
["may be ruled out for","INDICATION","","forward"],
["may be ruled out","INDICATION","","backward"],
["is to be ruled out for","INDICATION","","forward"],
["is to be ruled out","INDICATION","","backward"],
["rule him out","INDICATION","","forward"],
["might be ruled out for","INDICATION","","forward"],
["should be ruled out for","INDICATION","","forward"],
["rule her out","INDICATION","","forward"],
["not been ruled out","INDICATION","","backward"],
["might be ruled out","INDICATION","","backward"],
["rule patient out for","INDICATION",r"rule (him|her|patient|the patient|subject) out for","forward"],
["evaluation of","INDICATION",r"evaluation\s(of|for)","forward"],
["evaluation","INDICATION","","bidirectional"],
["being ruled out","INDICATION","","backward"],
["what must be ruled out is","INDICATION","","forward"],
["examination for","INDICATION",r"(study|exam|examination) for","forward"],
["study for detection","INDICATION","","forward"],
["examination","INDICATION",r"\b(examination|exam|study)\b","backward"],
["protocol",'INDICATION','','backward'],
["rule the patient out","INDICATION","","forward"],
["rule out for","INDICATION","","forward"],
["be ruled out for","INDICATION","","forward"],
["rule the patient out for","INDICATION","","forward"])

historicals = itemData(
["documented","HISTORICAL","","forward"],
["subacute","HISTORICAL","","forward"],
["chronic","HISTORICAL","","forward"],
["previous","HISTORICAL","","forward"], # fixes pedoc #98, 115
["resolving","HISTORICAL","","forward"],
["resolved","HISTORICAL","","backward"],
["previous","HISTORICAL","","forward"],
["interval change","HISTORICAL","","bidirectional"],
["resolution of","HISTORICAL","","forward"],
["clinical history","HISTORICAL","","forward"],
["unchanged","HISTORICAL","","bidirectional"],
["changing","HISTORICAL","","forward"],
["change in","HISTORICAL","","forward"],
["prior","HISTORICAL","","bidirectional"],
["diminished","HISTORICAL","","bidirectional"],
["again noted","HISTORICAL","","bidirectional"],
["sequelae of","HISTORICAL","","forward"],
["prior study", "HISTORICAL","","bidirectional"],
)

hypothetical = itemData(
["if","HYPOTHETICAL","","forward"],
["return","HYPOTHETICAL","","forward"],
["returning","HYPOTHETICAL","","forward"],
["should he","HYPOTHETICAL","","forward"],
["should she","HYPOTHETICAL","","forward"],
["call","HYPOTHETICAL","","forward"],
["should there","HYPOTHETICAL","","forward"],
["should the","HYPOTHETICAL","","forward"],
["as needed","HYPOTHETICAL","","forward"],
["come back for","HYPOTHETICAL","","forward"],
["come back to","HYPOTHETICAL","","forward"],
["look out for","HYPOTHETICAL","","forward"],
)

conjugates = itemData(
["involving","PRESENTATION","","terminate"], # proposed fix for pedoc #153
["as a secondary cause for","BECAUSE","","terminate"],
["as the secondary etiology for","ETIOLOGY","","terminate"],
["as a secondary source of","BECAUSE","","terminate"],
["as an ETIOLOGY of","ETIOLOGY ","","terminate"],
["as the secondary reason of","BECAUSE","","terminate"],
["as the secondary origin of","BECAUSE","","terminate"],
["as an secondary reason for","BECAUSE","","terminate"],
["as an secondary reason of","BECAUSE","","terminate"],
["reason for","BECAUSE","","terminate"],
["still","PRESENTATION","","terminate"],
["source of","BECAUSE","","terminate"],
["except","BUT","","terminate"],
["etiology of","ETIOLOGY ","","terminate"],
["as a cause of","BECAUSE","","terminate"],
["as a source of","BECAUSE","","terminate"],
["as the secondary etiology of","ETIOLOGY","","terminate"],
["as an reason for","BECAUSE","","terminate"],
["as a etiology for","ETIOLOGY","","terminate"],
["as a secondary origin for","BECAUSE","","terminate"],
["etiology for","ETIOLOGY","","terminate"],
["reasons for","BECAUSE","","terminate"],
["as a secondary cause of","BECAUSE","","terminate"],
["aside from","BUT","","terminate"],
["as the origin of","BECAUSE","","terminate"],
["though","BUT","","terminate"],
["which","WHICH","","terminate"],
["cause of","BECAUSE","","terminate"],
["as the secondary cause for","BECAUSE","","terminate"],
["as a source for","BECAUSE","","terminate"],
["as an origin for","BECAUSE","","terminate"],
["as a secondary origin of","BECAUSE","","terminate"],
["as the etiology for","ETIOLOGY","","terminate"],
["other possibilities of","BUT","","terminate"],
["as an etiology for","ETIOLOGY ","","terminate"],
["origins for","BECAUSE","","terminate"],
["as the secondary reason for","BECAUSE","","terminate"],
["as the secondary origin for","BECAUSE","","terminate"],
["as an reason of","BECAUSE","","terminate"],
["origin for","BECAUSE","","terminate"],
["as a cause for","BECAUSE","","terminate"],
["however","BUT","","terminate"],
["secondary to","BECAUSE","","terminate"],  #???
["although","BUT","","terminate"],
["as an secondary source of","BECAUSE","","terminate"],
["as an source of","BECAUSE","","terminate"],
["as an cause for","BECAUSE","","terminate"],
["as the secondary cause of","BECAUSE","","terminate"],
["as a secondary reason of","BECAUSE","","terminate"],
["as the etiology of","ETIOLOGY","","terminate"],
["as an source for","BECAUSE","","terminate"],
["as an secondary etiology of","ETIOLOGY","","terminate"],
["reasons of","BECAUSE","","terminate"],
["as an cause of","BECAUSE","","terminate"],
["as an secondary cause for","BECAUSE","","terminate"],
["as a reason of","BECAUSE","","terminate"],
["but","BUT","","terminate"],
["as the secondary source of","BECAUSE","","terminate"],
["as a etiology of","ETIOLOGY","","terminate"],
["reason of","BECAUSE","","terminate"],
["causes for","BECAUSE","","terminate"],
["yet","BUT","","terminate"],
["as a secondary etiology for","ETIOLOGY","","terminate"],
["as the origin for","BECAUSE","","terminate"],
["as the reason for","BECAUSE","","terminate"],
["trigger event for","BECAUSE","","terminate"],
["as the reason of","BECAUSE","","terminate"],
["cause for","BECAUSE","","terminate"],
["as a reason for","BECAUSE","","terminate"],
["as an secondary cause of","BECAUSE","","terminate"],
["sources of","BECAUSE","","terminate"],
["as the cause for","BECAUSE","","terminate"],
["as the source of","BECAUSE","","terminate"],
["as the source for","BECAUSE","","terminate"],
["origin of","BECAUSE","","terminate"],
["causes of","BECAUSE","","terminate"],
["sources for","BECAUSE","","terminate"],
["as a secondary source for","BECAUSE","","terminate"],
["apart from","BUT","","terminate"],
["source for","BECAUSE","","terminate"],
["as an secondary origin for","BECAUSE","","terminate"],
["origins of","BECAUSE","","terminate"],
["as an origin of","BECAUSE","","terminate"],
["as an secondary source for","BECAUSE","","terminate"],
["nevertheless","BUT","","terminate"],
["as the secondary source for","BECAUSE","","terminate"],
["as a secondary reason for","BECAUSE","","terminate"],
["as an secondary etiology for","ETIOLOGY","","terminate"],
["as the cause of","BECAUSE","","terminate"],
["as a secondary etiology of","ETIOLOGY","","terminate"],
["as an secondary origin of","BECAUSE","","terminate"])

probables = itemData(
["seen best","PROBABLE_EXISTENCE","",""], 
["consistent with","PROBABLE_EXISTENCE","","forward"],
["evidence","PROBABLE_EXISTENCE","","forward"],
["appear","PROBABLE_EXISTENCE","\bappear\b","bidirectional"],
["may represent","PROBABLE_EXISTENCE",r"""(may|might)\srepresent""","forward"],
["appears to be","PROBABLE_EXISTENCE","","forward"],
["compatible with","PROBABLE_EXISTENCE","","forward"],
["convincing","PROBABLE_EXISTENCE","","forward"],
["represents","PROBABLE_EXISTENCE","","forward"],
["certain if","UNCERTAINTY","","forward"],
["suspicious","PROBABLE_EXISTENCE","","forward"],
["seen","PROBABLE_EXISTENCE",r"(seen|visualized|observed|noted)","backward"],
["worrisome","PROBABLE_EXISTENCE","","forward"],
["identified","PROBABLE_EXISTENCE","","backward"],
["suspicous","PROBABLE_EXISTENCE","","forward"],
["likely","PROBABLE_EXISTENCE","","bidirectional"],
["versus","PROBABLE_EXISTENCE","versus|vs","bidirectional"],
["possible","PROBABLE_EXISTENCE","possible|possibly","bidirectional"],
["equivocal","PROBABLE_EXISTENCE","",'bidirectional']
)

definites = itemData(
["positive examination for","DEFINITE_EXISTENCE","","forward"], # fixes pedoc #126 uncertainty
["obvious","DEFINITE_EXISTENCE","","forward"],
["definite","DEFINITE_EXISTENCE","","forward"],
["positive study for","PSEDUONEG",r"positive (study|exam|examination)( for)","forward"],
)


findings = itemData(
)

experiencers = itemData(
["father","OTHER","\bfather\b","forward"],
["mother","OTHER","\bmother\b","forward"],
["grandmother's","OTHER","\bgrandmother's\b","forward"],
["grandfather's","OTHER","\bgrandfather's\b","forward"],
["uncle's","OTHER","\buncle's\b","forward"],
["aunt's","OTHER","\baunt's\b","forward"],
["roommate's","OTHER","\broommate's\b","forward"],
["brother's","OTHER","\bbrother's\b","forward"],
["sister's","OTHER","\bsister's\b","forward"],
["dad's","OTHER","\bdad's\b","forward"],
["mom's","OTHER","\bmom's\b","forward"],
["mother's","OTHER","\bmother's\b","forward"],
["father's","OTHER","\bfather's\b","forward"],
["wife","OTHER","\bwife\b","forward"],
["husband","OTHER","\bhusband\b","forward"],
["grandmother","OTHER","\bgrandmother\b","forward"],
["grandfather","OTHER","\bgrandfather\b","forward"],
["uncle","OTHER","\buncle\b","forward"],
["aunt","OTHER","\baunt\b","forward"],
["roommate","OTHER","\broommate\b","forward"],
["brother","OTHER","\bbrother\b","forward"],
["sister","OTHER","\bsister\b","forward"],
["dad","OTHER","\bdad\b","forward"],
["mom","OTHER","\bmom\b","forward"],
["family history","OTHER","\bfamily history\b","forward"],
["wife's","OTHER","\bwife's\b","forward"],
["husband's","OTHER","\bhusband's\b","forward"],
)


pseudoexperiencers = itemData(
["by her husband","OTHER","\bby her husband\b","forward"],
["by his wife","OTHER","\bby his wife\b","forward"],
["for the","OTHER","\bfor the\b","forward"],
["for a","OTHER","\bfor a\b","forward"]
)